### ISSUE TITLE
Utils.cpp GetMonthDayCount Leap Year Calculation

### ISSUE THREAD

**Issue by Mortdecai** [A-G-D/Calendar#1]
In the Gregorian calendar, three criteria must be taken into account to identify leap years:

The year must be evenly divisible by 4;
If the year can be evenly divided by 100, it is not a leap year; unless,
The year is also evenly divisible by 400. Then it is a leap year.
According to these rules, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300, and 2500 are not leap years.

[https://www.timeanddate.com/date/leapyear.html]

**Comment by A-G-D** [comment]
Noted
